### ISSUE TITLE
Improve Data Collection Experience

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/autohack-idle#16]
Currently, there are some issues with the data collection. It does not look very appealing - it is simply text appearing on the screen. Here are some ideas:

- Create a more compelling background/screen
- Create graphics for each bit (like coins or something, still with `1`s or `0`s on them)
- Make the bits hover or move enticingly
- Create a pleasant "collection" experience when a bit is tapped

At this point, the collection of bits is the primary gameplay - it should be engaging and compelling.

**Comment by josephmaxwellhyland** [comment]
This will involve the Phaser library quite a bit, but it will be a good opportunity to make a visual change. It could still be relatively simple - even just adding a circle around each number, or allowing for both `0` and `1` instead of just `1`.

After the basics, adding some little touches like animation/movement could be cool, like this:

![](https://i.pinimg.com/originals/3a/d0/e1/3ad0e1a0151b66d3879c74ca43d29269.gif)

or this:

![](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b64e3418-6184-4888-838d-d8b8cf3690a3/daeaom3-6e755667-6ca3-4f4d-a4aa-0468f05cab5c.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2I2NGUzNDE4LTYxODQtNDg4OC04MzhkLWQ4YjhjZjM2OTBhM1wvZGFlYW9tMy02ZTc1NTY2Ny02Y2EzLTRmNGQtYTRhYS0wNDY4ZjA1Y2FiNWMuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.8z_B-T2Nb7V4xU11ICjpTbG8N4kP9uqK8qk5Yot6iq4)

**Comment by kavyab2006** [comment]
Meeting Notes
- Upgrades: sweep, robot collection
- Have falling green 1s and 0s
- Background: terminal
- Apps: terminal, user info, upgrades, settings, store(cosmetics), learning, restart(reset)
- Colors --> dark cool colors: green, black(terminal), dark blue(computer background), dark purple(shop), 
- Sprites: icons for apps
- Use coin as shop app icon
- Have a computer screen or iPhone screen with different clickable apps
- Have a log in screen with a guest option
- Music: base/main screen, able to buy more tracks, sound effects
- Have a credits page
- For now: have single color buttons
