### ISSUE TITLE
Think of Good Name for Currency

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/autohack-idle#24]
The currency collected in the game should have a good name, like "HackerCoin" but that of course already exists. Think of a cool name for it.

**Comment by Dan-Quin** [comment]
Added a name from my test branch that got merged, if we want to go back and change it that's fine but we have something that works for now.

**Comment by josephmaxwellhyland** [comment]
It's CodeCash (or PixelPayout but no) (ok maybe)
