### ISSUE TITLE
Add PWA Wrapper: Make Installable

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/autohack-idle#29]
Players should be able to install the web app as a mobile app using [Progressive Web App](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) technology.

**Comment by josephmaxwellhyland** [comment]
This will likely not be happening during this summer - the team decided to focus solely on the Desktop version of the application for now.

**Comment by jvgusch** [comment]
Will not do. Focusing on desktop experience only at this moment.
