### ISSUE TITLE
Change CSS to be More Flexible

### ISSUE THREAD

**Issue by JudeKlatte** [hto-projects/autohack-idle#68]
As it stands. the CSS for AHI is a little wonky. When the browser is enlarged from a small state, the blue background is only in the middle, with a white background behind the boxes.  The CSS should be changed so that it smoothly transitions between smaller and larger sizes.

Also, the two boxes are very large compared to the rest of the screen when shrunk, making it hard to see the entire screen. The boxes do not have a button form until shrunk to a width of 600px or less, so there should also be a size for the boxes when they are in-between full-screen and 600px.

![Image](https://github.com/hto-projects/autohack-idle/assets/98344262/f1f0f71a-29e7-40eb-8f3a-7d2d32a7af9f)

![Image](https://github.com/hto-projects/autohack-idle/assets/98344262/c4059063-e7c7-416b-be34-6bda8e85b35a)

**Comment by josephmaxwellhyland** [comment]
This doesn't really apply anymore with our new ux!
