### ISSUE TITLE
Fix Upgrading Before Gameplay

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/autohack-idle#70]
Currently, when starting from a fresh game, purchasing the "Check for Bits" and "Chance for Bits" upgrades _before_ entering the game will not make bits appear. Steps:

1. Run the app
2. Open the app in an incognito window
3. On the initial screen, purchase the "Check for Bits" and "Chance for Bits" upgrades
4. Enter the game
5. Notice no bits appear

This may not be relevant if we decide to get rid of the two basic upgrades, or rethink the game's introduction.

**Comment by MangoMagoCane** [comment]
This may have been fixed with the major `Desktop` component refactoring we did

**Comment by josephmaxwellhyland** [comment]
Issue is not appearing at this time.
