### ISSUE TITLE
Email is case sensitive

### ISSUE THREAD

**Issue by Arrowship06** [hto-projects/autohack-idle#81]
When you input your email it saves it as case sensitive. So if you put in Magic@gmail.com you cannot log in with magic@gmail.com or Magic@Gmail.com.

**Comment by josephmaxwellhyland** [comment]
This should be a backend change - when registering for an account, the email should be saved in all lowercase. then, when signing in, the email input should be converted to all lowercase and compared to the all-lowercase email stored in the db.
