### ISSUE TITLE
Email can be an absurd amount of characters long and overlaps the game screen.

### ISSUE THREAD

**Issue by Arrowship06** [hto-projects/autohack-idle#90]

**Comment by Arrowship06** [comment]
![Image](https://github.com/hto-projects/autohack-idle/assets/102868134/376072c4-2cec-4e5f-b86c-c20af96e8958)

**Comment by josephmaxwellhyland** [comment]
You could add a max number of characters in the user registration form. this issue is currently not available because the user info is not surfaced anywhere.
