### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/autohack-idle#95]
Currently there is no favicon. let's add one

**Comment by josephmaxwellhyland** [comment]
We could probably add some other metadata and stuff too. nbd tho

**Comment by emadsu** [comment]
BitMiner 




![Image](https://github.com/hto-projects/autohack-idle/assets/109160381/d7aa1c72-b74e-4332-88ee-2d3ce655bd74)
